plugins:
  - serverless-esbuild

custom:
  secrets: ${file(./config/${opt:stage, 'dev'}.json)}

service: ${self:custom.secrets.service.name}

frameworkVersion: "3"

provider:
  name: ${self:custom.secrets.provider.name}
  runtime: ${self:custom.secrets.provider.runtime}
  stage: ${self:custom.secrets.provider.stage, 'dev'}
  region: ${self:custom.secrets.provider.region}
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    BOT_NAME: ${self:custom.secrets.provider.environment.BOT_NAME}-${self:provider.stage}
    BOT_USERNAME: ${self:custom.secrets.provider.environment.BOT_USERNAME}
    TELEGRAM_BOT_TOKEN: ${self:custom.secrets.provider.environment.TELEGRAM_BOT_TOKEN}
    AUTH_URL: ${self:custom.secrets.provider.environment.AUTH_URL}
    MONGO_USER: ${self:custom.secrets.provider.environment.MONGO_USER}
    MONGO_PASSWORD: ${self:custom.secrets.provider.environment.MONGO_PASSWORD}
    MONGO_HOST: ${self:custom.secrets.provider.environment.MONGO_HOST}
    MONGO_DATABASE: ${self:custom.secrets.provider.environment.MONGO_DATABASE}

functions:
  telegramAuthorizer: ${file(./src/functions/telegram_authorizer/function.yml)}
  telegramSetWebhook: ${file(./src/functions/telegram_set_webhook/function.yml)}
  telegramWebhook: ${file(./src/functions/telegram_webhook/function.yml)}
  telegramSendMessage: ${file(./src/functions/telegram_send_message/function.yml)}
  telegramEditMessage: ${file(./src/functions/telegram_edit_message/function.yml)}
  telegramSendPhoto: ${file(./src/functions/telegram_send_photo/function.yml)}
  telegramDebug: ${file(./src/functions/telegram_debug/function.yml)}
  telegramGetChats: ${file(./src/functions/telegram_get_chats/function.yml)}
  telegramCleanReplyMarkup: ${file(./src/functions/telegram_clean_reply_markup/function.yml)}
  telegramMembersMute: ${file(./src/functions/telegram_members_mute/function.yml)}
  telegramMembersUnmute: ${file(./src/functions/telegram_members_unmute/function.yml)}
